# Nome da Aplicação
spring.application.name=gerenciador-assinaturas

# ===============================================
# CONFIGURAÇÃO DO SERVIDOR
# ===============================================
server.port=8081

# ===============================================
# CONFIGURAÇÃO DO BANCO DE DADOS (DATASOURCE)
# ===============================================
spring.datasource.url=jdbc:postgresql://localhost:5432/gerenciador_assinaturas

spring.datasource.username=postgres
spring.datasource.password=123abc

# ===============================================
# CONFIGURAÇÃO DO FLYWAY
# ===============================================
spring.flyway.enabled=true

# ===============================================
# CONFIGURAÇÃO DO HIBERNATE (JPA)
# ===============================================
spring.jpa.hibernate.ddl-auto=validate

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true