# Nome da Aplica豫o
spring.application.name=gerenciador-assinaturas
server.servlet.context-path=/gerenciador-assinaturas

# ===============================================
# CONFIGURA플O DO SERVIDOR
# ===============================================
server.port=8081

# ===============================================
# CONFIGURA플O DO BANCO DE DADOS (DATASOURCE)
# ===============================================
spring.datasource.url=jdbc:postgresql://localhost:5432/gerenciador_assinaturas

spring.datasource.username=postgres
spring.datasource.password=123abc

# ===============================================
# CONFIGURA플O DO FLYWAY
# ===============================================
spring.flyway.enabled=true

# ===============================================
# CONFIGURA플O DO HIBERNATE (JPA)
# ===============================================
spring.jpa.hibernate.ddl-auto=validate

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# ===============================================
# CONFIGURA플O DE EXIBI플O DE ERROS
# ===============================================
server.error.include-stacktrace=never

# ===============================================
# CONFIGURA플O SpringDoc OpenAPI
# ===============================================
springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.path=/api-docs
