-- Flyway Migration: V1
-- Título: Criação das Tabelas do Sistema



-- Tabela 1: USUARIO
-- Armazena os dados de login de cada usuário.
CREATE TABLE usuario (
    id_usuario BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    nome VARCHAR(150) NOT NULL,
    email VARCHAR(255) NOT NULL UNIQUE,
    senha_hash VARCHAR(255) NOT NULL
);


-- Tabela 2: CATEGORIA
-- Armazena as categorias globais para organizar as assinaturas.
CREATE TABLE categoria (
    id_categoria BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    nome VARCHAR(50) NOT NULL UNIQUE
);


-- Tabela 3: METODO_PAGAMENTO
-- Armazena as formas de pagamento cadastradas pelo usuário.
CREATE TABLE metodo_pagamento (
    id_metodo_pago BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    nome_personalizado VARCHAR(50) NOT NULL,
    tipo VARCHAR(30) NOT NULL,
    info_adicional VARCHAR(50),
    id_usuario BIGINT NOT NULL,
    CONSTRAINT fk_metodo_pagamento_usuario FOREIGN KEY (id_usuario) REFERENCES USUARIO(id_usuario)
);


-- Tabela 4: TAG
-- Armazena as tags globais para organização flexível.
CREATE TABLE tag (
    id_tag BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    nome VARCHAR(50) NOT NULL UNIQUE
);


-- Tabela 5: ASSINATURA
-- A entidade central do sistema, armazena cada assinatura.
CREATE TABLE assinatura (
    id_assinatura BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    nome VARCHAR(100) NOT NULL,
    valor DECIMAL(10, 2) NOT NULL,
    ciclo_pagamento VARCHAR(30) NOT NULL,
    proxima_cobranca DATE NOT NULL,
    id_usuario BIGINT NOT NULL,
    id_categoria BIGINT NOT NULL,
    id_metodo_pago BIGINT,
    CONSTRAINT fk_assinatura_usuario FOREIGN KEY (id_usuario) REFERENCES USUARIO(id_usuario),
    CONSTRAINT fk_assinatura_categoria FOREIGN KEY (id_categoria) REFERENCES CATEGORIA(id_categoria),
    CONSTRAINT fk_assinatura_metodo_pagamento FOREIGN KEY (id_metodo_pago) REFERENCES METODO_PAGAMENTO(id_metodo_pago)
);


-- Tabela 6: PAGAMENTO
-- Armazena o histórico de todas as cobranças que já ocorreram.
CREATE TABLE pagamento (
    id_pagamento BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    data_pagamento TIMESTAMP WITH TIME ZONE NOT NULL,
    valor_pago DECIMAL(10, 2) NOT NULL,
    id_assinatura BIGINT NOT NULL,
    CONSTRAINT fk_pagamento_assinatura FOREIGN KEY (id_assinatura) REFERENCES ASSINATURA(id_assinatura)
);


-- Tabela 7: ASSINATURA_TAG (Tabela de Junção para a relação N-N)
-- Conecta Assinaturas e Tags.
CREATE TABLE assinatura_tag (
    id_assinatura BIGINT NOT NULL,
    id_tag BIGINT NOT NULL,
    CONSTRAINT pk_assinatura_tag PRIMARY KEY (id_assinatura, id_tag),
    CONSTRAINT fk_assinatura_tag_assinatura FOREIGN KEY (id_assinatura) REFERENCES ASSINATURA(id_assinatura),
    CONSTRAINT fk_assinatura_tag_tag FOREIGN KEY (id_tag) REFERENCES TAG(id_tag)
);
